service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev
  region: eu-west-1

functions:
  products:
    handler: products.getProductsList
    events:
      - http:
          path: products
          method: get
  productsById:
    handler: productsById.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
